name: pyramakerz_task
description: "A new Flutter project."


publish_to: 'none' 


version: 1.0.0+1

environment:
  sdk: ^3.5.0



dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  # state management
  flutter_bloc: ^8.1.6
  # to create voice commands by user
  speech_to_text: ^7.0.0
  # to navigate using Navigator 2
  go_router: ^14.6.1
  # to gengerate code
  freezed_annotation: ^2.4.4
  json_annotation: ^4.9.0
  # localization
  easy_localization: ^3.0.7
  # to save user data in locale storage
  shared_preferences: ^2.3.3
  # dependency injection
  get_it: ^8.0.2
  # to preview camera stream realtime as widget
  camera: ^0.11.0+2
  # to load dataset from tensorflow models
  # flutter_tflite: ^1.0.1
  tflite_v2: ^1.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^4.0.0
  build_runner: ^2.4.13
  freezed: ^2.5.7

flutter:

  
  uses-material-design: true
  assets:
    - lib/config/localization/
    - assets/object_dataset/
  
  
  
  

 